#!/usr/bin/env python3
"""The gate that runs before any behavioural test.

A syntax error in bin/agentbus or bin/ab-hook, or a hook wired to an event the
engine does not implement, does not fail this repository — it fails every
Claude Code session on the machine, mid-task. So these four checks come first
and everything else is only meaningful once they pass.

Prints one `ok <what>` line per check; exits non-zero on the first failure.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.environ.get("AB_ROOT") or os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))

failed = []


def ok(what):
    print("ok %s" % what)


def bad(what, detail):
    print("FAIL %s\n%s" % (what, detail))
    failed.append(what)


def check_engine_compiles():
    import py_compile
    out = os.path.join(tempfile.mkdtemp(), "agentbus.pyc")
    try:
        py_compile.compile(os.path.join(ROOT, "bin", "agentbus"),
                           cfile=out, doraise=True)
    except Exception as exc:
        return bad("bin/agentbus compiles", str(exc))
    ok("bin/agentbus compiles")


def check_fastpath_parses():
    if not os.path.exists("/bin/bash") and not _which("bash"):
        return ok("bin/ab-hook parses (skipped: no bash)")
    res = subprocess.run(["bash", "-n", os.path.join(ROOT, "bin", "ab-hook")],
                         capture_output=True, text=True)
    if res.returncode != 0:
        return bad("bin/ab-hook parses", res.stderr.strip())
    ok("bin/ab-hook parses")


def _which(name):
    from shutil import which
    return which(name)


def _wiring(cfg):
    """{Claude Code event: [(matcher, agent-bus event) …]} for one hook file.

    The two entry points express the same thing differently: the POSIX file puts
    the event at the end of a shell command line, the Python one passes it in
    `args`. Both are reduced to the same shape so they can be compared."""
    out = {}
    for event, entries in sorted(cfg.get("hooks", {}).items()):
        for entry in entries:
            for hook in entry.get("hooks", []):
                args = hook.get("args")
                if args:
                    name = args[-1]
                else:
                    m = re.search(r"\s([a-z][a-z-]+)\s*$", hook.get("command", ""))
                    name = m.group(1) if m else "?"
                out.setdefault(event, []).append((entry.get("matcher", ""), name))
    return out


def check_hook_wiring():
    """Every event the hook files call must exist in the engine, and the two
    entry points must call the same ones.

    hooks/hooks.json is generated by the installer and git-ignored. When it is
    present it must agree with the source it was generated from — a mismatch
    means somebody edited the wiring and did not re-run ./install.sh, and the
    change is not actually live in any session."""
    engine = open(os.path.join(ROOT, "bin", "agentbus")).read()
    block = re.search(r"^HOOKS = \{(.*?)^\}", engine, re.S | re.M)
    if not block:
        return bad("the engine declares HOOKS", "no HOOKS dict in bin/agentbus")
    known = set(re.findall(r'"([a-z-]+)":', block.group(1)))
    if not known:
        return bad("the engine declares HOOKS", "HOOKS is empty")
    ok("the engine declares %d hook events" % len(known))

    wiring = {}
    for name in ("hooks.posix.json", "hooks.python.json", "hooks.json"):
        path = os.path.join(ROOT, "hooks", name)
        if not os.path.exists(path):
            continue
        try:
            cfg = json.load(open(path))
        except ValueError as exc:
            bad("hooks/%s is valid JSON" % name, str(exc))
            continue
        ok("hooks/%s is valid JSON" % name)
        wiring[name] = _wiring(cfg)
        called = {n for pairs in wiring[name].values() for _, n in pairs}
        unknown = sorted(called - known)
        if unknown:
            bad("hooks/%s calls only known events" % name,
                "the engine has no handler for: %s" % ", ".join(unknown))
        elif not called:
            bad("hooks/%s wires anything at all" % name, "no hook commands found")
        else:
            ok("hooks/%s calls only known events (%d)" % (name, len(called)))

    if "hooks.posix.json" in wiring and "hooks.python.json" in wiring:
        if wiring["hooks.posix.json"] != wiring["hooks.python.json"]:
            bad("the shell and Python entry points wire the same events",
                "posix : %s\npython: %s" % (wiring["hooks.posix.json"],
                                            wiring["hooks.python.json"]))
        else:
            ok("the shell and Python entry points wire the same events")

    if "hooks.json" in wiring:
        sources = [w for n, w in wiring.items() if n != "hooks.json"]
        if wiring["hooks.json"] not in sources:
            bad("hooks/hooks.json is up to date",
                "the generated wiring matches neither source — run ./install.sh, "
                "then /reload-plugins in each running session, or the change is "
                "not live anywhere")
        else:
            ok("hooks/hooks.json is up to date with its source")


def check_no_stray_output():
    """A hook must print nothing, or valid JSON. One stray `print` in a helper
    corrupts the session's view of every hook result, and it stays invisible
    until somebody's session breaks — so writing to stdout is confined to the
    CLI verbs and the two functions that emit hook JSON, and anything else that
    wants to say something must say it on stderr."""
    import ast
    tree = ast.parse(open(os.path.join(ROOT, "bin", "agentbus")).read())
    allowed = ("deny", "note_ctx", "main")
    offenders = []
    for top in tree.body:
        if not isinstance(top, ast.FunctionDef):
            continue
        if top.name.startswith(("cli_", "hook_")) or top.name in allowed:
            continue
        for sub in ast.walk(top):
            if not isinstance(sub, ast.Call):
                continue
            if getattr(sub.func, "id", "") != "print":
                continue
            if any(kw.arg == "file" for kw in sub.keywords):
                continue          # stderr never reaches the session's parser
            offenders.append("line %d: print() to stdout in %s()"
                             % (sub.lineno, top.name))
    if offenders:
        return bad("nothing prints to stdout outside the CLI and hook emitters",
                   "\n".join(offenders))
    ok("nothing prints to stdout outside the CLI and hook emitters")


def main():
    check_engine_compiles()
    check_fastpath_parses()
    check_hook_wiring()
    check_no_stray_output()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
