#!/usr/bin/env python3
"""The gate that runs before any behavioural test.

A syntax error in bin/agentbus or bin/ab-hook, or a hook wired to an event the
engine does not implement, does not fail this repository — it fails every
Claude Code session on the machine, mid-task. So these four checks come first
and everything else is only meaningful once they pass.

Prints one `ok <what>` line per check; exits non-zero on the first failure.
"""

import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.environ.get("AB_ROOT") or os.path.dirname(
    os.path.dirname(os.path.abspath(__file__)))

failed = []


def ok(what):
    print("ok %s" % what)


def bad(what, detail):
    print("FAIL %s\n%s" % (what, detail))
    failed.append(what)


def check_engine_compiles():
    import py_compile
    out = os.path.join(tempfile.mkdtemp(), "agentbus.pyc")
    try:
        py_compile.compile(os.path.join(ROOT, "bin", "agentbus"),
                           cfile=out, doraise=True)
    except Exception as exc:
        return bad("bin/agentbus compiles", str(exc))
    ok("bin/agentbus compiles")


def check_fastpath_parses():
    if not os.path.exists("/bin/bash") and not _which("bash"):
        return ok("bin/ab-hook parses (skipped: no bash)")
    res = subprocess.run(["bash", "-n", os.path.join(ROOT, "bin", "ab-hook")],
                         capture_output=True, text=True)
    if res.returncode != 0:
        return bad("bin/ab-hook parses", res.stderr.strip())
    ok("bin/ab-hook parses")


def _which(name):
    from shutil import which
    return which(name)


def _wiring(cfg):
    """{Claude Code event: [(matcher, agent-bus event) …]} for one hook file.

    The two entry points express the same thing differently: the POSIX file puts
    the event at the end of a shell command line, the Python one passes it in
    `args`. Both are reduced to the same shape so they can be compared."""
    out = {}
    for event, entries in sorted(cfg.get("hooks", {}).items()):
        for entry in entries:
            for hook in entry.get("hooks", []):
                args = hook.get("args")
                if args:
                    name = args[-1]
                else:
                    m = re.search(r"\s([a-z][a-z-]+)\s*$", hook.get("command", ""))
                    name = m.group(1) if m else "?"
                out.setdefault(event, []).append((entry.get("matcher", ""), name))
    return out


def check_hook_wiring():
    """Every event the hook files call must exist in the engine, and the two
    entry points must call the same ones.

    hooks/hooks.json is generated by the installer and git-ignored. When it is
    present it must agree with the source it was generated from — a mismatch
    means somebody edited the wiring and did not re-run ./install.sh, and the
    change is not actually live in any session."""
    engine = open(os.path.join(ROOT, "bin", "agentbus")).read()
    block = re.search(r"^HOOKS = \{(.*?)^\}", engine, re.S | re.M)
    if not block:
        return bad("the engine declares HOOKS", "no HOOKS dict in bin/agentbus")
    known = set(re.findall(r'"([a-z-]+)":', block.group(1)))
    if not known:
        return bad("the engine declares HOOKS", "HOOKS is empty")
    ok("the engine declares %d hook events" % len(known))

    wiring = {}
    for name in ("hooks.posix.json", "hooks.python.json", "hooks.json"):
        path = os.path.join(ROOT, "hooks", name)
        if not os.path.exists(path):
            continue
        try:
            cfg = json.load(open(path))
        except ValueError as exc:
            bad("hooks/%s is valid JSON" % name, str(exc))
            continue
        ok("hooks/%s is valid JSON" % name)
        wiring[name] = _wiring(cfg)
        called = {n for pairs in wiring[name].values() for _, n in pairs}
        unknown = sorted(called - known)
        if unknown:
            bad("hooks/%s calls only known events" % name,
                "the engine has no handler for: %s" % ", ".join(unknown))
        elif not called:
            bad("hooks/%s wires anything at all" % name, "no hook commands found")
        else:
            ok("hooks/%s calls only known events (%d)" % (name, len(called)))

    if "hooks.posix.json" in wiring and "hooks.python.json" in wiring:
        if wiring["hooks.posix.json"] != wiring["hooks.python.json"]:
            bad("the shell and Python entry points wire the same events",
                "posix : %s\npython: %s" % (wiring["hooks.posix.json"],
                                            wiring["hooks.python.json"]))
        else:
            ok("the shell and Python entry points wire the same events")

    if "hooks.json" in wiring:
        sources = [w for n, w in wiring.items() if n != "hooks.json"]
        if wiring["hooks.json"] not in sources:
            bad("hooks/hooks.json is up to date",
                "the generated wiring matches neither source — run ./install.sh, "
                "then /reload-plugins in each running session, or the change is "
                "not live anywhere")
        else:
            ok("hooks/hooks.json is up to date with its source")


def check_no_stray_output():
    """A hook must print nothing, or valid JSON. One stray `print` in a helper
    corrupts the session's view of every hook result, and it stays invisible
    until somebody's session breaks — so writing to stdout is confined to the
    CLI verbs and the two functions that emit hook JSON, and anything else that
    wants to say something must say it on stderr."""
    import ast
    tree = ast.parse(open(os.path.join(ROOT, "bin", "agentbus")).read())
    allowed = ("deny", "note_ctx", "main")
    offenders = []
    for top in tree.body:
        if not isinstance(top, ast.FunctionDef):
            continue
        if top.name.startswith(("cli_", "hook_")) or top.name in allowed:
            continue
        for sub in ast.walk(top):
            if not isinstance(sub, ast.Call):
                continue
            if getattr(sub.func, "id", "") != "print":
                continue
            if any(kw.arg == "file" for kw in sub.keywords):
                continue          # stderr never reaches the session's parser
            offenders.append("line %d: print() to stdout in %s()"
                             % (sub.lineno, top.name))
    if offenders:
        return bad("nothing prints to stdout outside the CLI and hook emitters",
                   "\n".join(offenders))
    ok("nothing prints to stdout outside the CLI and hook emitters")


def check_one_resolver():
    """"Who is acting and where" is answered in `resolve_party` and nowhere else.

    Thirteen functions used to answer it between them, and the order they were
    applied in lived at each call site rather than anywhere a reader could check
    it. Six of this plugin's twenty-two defects came out of the disagreements —
    among them a guard that applied `git -C <path>` by calling the very function
    whose pin check discarded it, and an `agentbus here` that pinned the record
    `status` prints while the guard went on deciding from the payload's cwd.

    The five inference helpers are private to `resolve_party` now; this is what
    keeps them private. A grep would be gameable by renaming a local, and the
    mistake is not made deliberately anyway: it is made by a hook that wants a
    subagent's root and reaches for the nearest function that has one, which is
    exactly how the spine grew to thirteen functions the first time."""
    import ast
    tree = ast.parse(open(os.path.join(ROOT, "bin", "agentbus")).read())
    what = "the who-and-where helpers are private to resolve_party"
    private = {"_follow_cwd", "_caller_view", "_party_view",
               "_follow_agent_cwd", "_command_worktree"}
    # They may call each other: a subagent's view is its record followed to
    # where it is working, which is one lookup and not two.
    allowed = private | {"resolve_party"}
    defined, offenders = set(), []
    for top in tree.body:
        if not isinstance(top, ast.FunctionDef):
            continue
        if top.name in private:
            defined.add(top.name)
        if top.name in allowed:
            continue
        for sub in ast.walk(top):
            if isinstance(sub, ast.Call) and getattr(sub.func, "id", "") in private:
                offenders.append("line %d: %s() called from %s()"
                                 % (sub.lineno, sub.func.id, top.name))
    missing = sorted(private - defined)
    if missing:
        # Renaming one would make this check pass by having nothing to look for.
        return bad(what, "no such function in the engine: %s" % ", ".join(missing))
    if offenders:
        return bad(what, "\n".join(offenders))
    ok(what)


def check_exits_are_planned():
    """A block message may not compose a command line of its own.

    Six of this plugin's twenty-two defects came from "what does this command
    touch and under what name is it locked" being answered in more than one
    place, and the place that hurt was the English at the bottom of a block. It
    gave a different answer from the guard that printed it three times:
    `agentbus wait <res>` was advertised and then refused; `agentbus claim
    worktree` was advertised, allowed, and wrote a lock nothing read; a block
    about one simulator advertised the bare resource, so its exit took a lock
    nothing was contending for and left the device where it was.

    `render_block` places `plan["exits"]` and composes nothing, which is what
    makes advice the guard would refuse unavailable rather than merely absent.
    This is what keeps it that way. The mistake is not made deliberately — it is
    made by somebody adding one more helpful line to a message — so a grep in a
    review would not catch it and a rename would not slip past this.

    The second half is about one block in particular. The serving block offers
    no way of stepping over the decision, because "I really do mean the other
    checkout's server" is not something anybody means: a green result belonging
    to another worktree is the founding failure this plugin exists for. A
    message that merely happens not to say AGENTBUS_OFF today is one exit away
    from saying it tomorrow, so the check is on the exits."""
    import ast
    tree = ast.parse(open(os.path.join(ROOT, "bin", "agentbus")).read())
    what = "block messages are rendered from a Plan's exits, not written out"
    fns = {t.name: t for t in tree.body if isinstance(t, ast.FunctionDef)}
    wanted = ("render_block", "serving_check", "_exit")
    missing = [n for n in wanted if n not in fns]
    if missing:
        # Renaming one would make this check pass by having nothing to look for.
        return bad(what, "no such function in the engine: %s" % ", ".join(missing))
    offenders = []
    for sub in ast.walk(fns["render_block"]):
        if not isinstance(sub, ast.Constant) or not isinstance(sub.value, str):
            continue
        if "agentbus " in sub.value or "AGENTBUS_OFF" in sub.value:
            offenders.append("line %d: render_block() spells out a command — %r"
                             % (sub.lineno, sub.value.strip()[:60]))
    for sub in ast.walk(fns["serving_check"]):
        if not isinstance(sub, ast.Call) or getattr(sub.func, "id", "") != "_exit":
            continue
        kind = sub.args[1] if len(sub.args) > 1 else None
        if isinstance(kind, ast.Constant) and kind.value == "bypass":
            offenders.append("line %d: serving_check() offers a bypass"
                             % sub.lineno)
    if offenders:
        return bad(what, "\n".join(offenders))
    ok(what)


def main():
    check_engine_compiles()
    check_fastpath_parses()
    check_hook_wiring()
    check_no_stray_output()
    check_one_resolver()
    check_exits_are_planned()
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
